# Generated by Django 5.2.6 on 2025-09-20 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_subcategory_sub_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
