# Generated by Django 5.2.6 on 2025-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_lesson_title_en_lesson_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
