# Generated by Django 5.2.6 on 2025-09-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_remove_userprofile_language_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('russian', 'russian'), ('english ', 'english'), ('kyrgyz', 'kyrgyz'), ('german', 'german'), ('france', 'france')], default='russian', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_categories', to='course_app.subcategory'),
        ),
    ]
