# Generated by Django 5.2.6 on 2025-09-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_alter_course_language_alter_course_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_categories_course', to='course_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='course_app.category'),
        ),
    ]
