# Generated by Django 5.2.6 on 2025-09-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_alter_course_sub_category_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='course',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_course', to='course_app.subcategory'),
            preserve_default=False,
        ),
    ]
