# Generated by Django 5.2.6 on 2025-09-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_remove_course_sub_category_course_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='course',
            name='sub_category',
            field=models.ManyToManyField(related_name='sub_category_course', to='course_app.subcategory'),
        ),
    ]
