# Generated by Django 5.2.6 on 2025-09-27 01:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0015_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('russian', 'russian'), ('english ', 'english'), ('kyrgyz', 'kyrgyz'), ('german', 'german'), ('france', 'france')], default='russian', max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('beginner ', 'beginner'), ('middle', 'middle'), ('advanced', 'advanced')], max_length=32),
        ),
    ]
