# Generated by Django 5.2.6 on 2025-09-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0016_alter_course_language_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
