# Generated by Django 5.2.6 on 2025-09-27 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0017_alter_option_option_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='questions',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options0', to='course_app.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions0', to='course_app.exam'),
        ),
    ]
