# Generated by Django 5.2.6 on 2025-09-27 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0017_alter_option_option_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='questions',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=50)),
                ('question_title_en', models.CharField(max_length=50, null=True)),
                ('question_title_ru', models.CharField(max_length=50, null=True)),
                ('passing_score', models.PositiveSmallIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course_app.exam')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course_app.question'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
