# Generated by Django 5.2.6 on 2025-09-27 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0018_remove_option_questions_question_option_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=50)),
                ('question_title_en', models.CharField(max_length=50, null=True)),
                ('question_title_ru', models.CharField(max_length=50, null=True)),
                ('passing_score', models.PositiveSmallIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionss', to='course_app.exam')),
            ],
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.questions'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
